from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class ValidationResult(BaseModel):
    is_valid: bool = Field(..., description="Whether the query passed validation")
    errors: List[str] = Field(default_factory=list, description="List of validation errors")
    warnings: List[str] = Field(default_factory=list, description="List of validation warnings")

class QueryResult(BaseModel):
    columns: List[str] = Field(..., description="List of column names returned by query")
    rows: List[Dict[str, Any]] = Field(..., description="Result rows as list of dictionaries")
    row_count: int = Field(..., description="Total number of rows returned")
    execution_time_ms: float = Field(..., description="Execution time in milliseconds")

class ColumnInfo(BaseModel):
    name: str = Field(..., description="Column name")
    type: str = Field(..., description="Data type of the column")
    nullable: bool = Field(..., description="Whether the column allows NULL values")

class ForeignKeyInfo(BaseModel):
    column: str = Field(..., description="Local column name")
    referred_table: str = Field(..., description="Referenced table name")
    referred_column: str = Field(..., description="Referenced column name")

class TableInfo(BaseModel):
    name: str = Field(..., description="Table name")
    columns: List[ColumnInfo] = Field(..., description="List of columns in the table")
    primary_keys: List[str] = Field(..., description="List of primary key column names")
    foreign_keys: List[ForeignKeyInfo] = Field(default_factory=list, description="List of foreign keys")

class SchemaInfo(BaseModel):
    tables: List[TableInfo] = Field(..., description="List of all tables in the schema")

class ChatResponse(BaseModel):
    question: str = Field(..., description="The original question")
    generated_sql: str = Field(..., description="The SQL generated by the AI")
    validation: ValidationResult = Field(..., description="Validation results for the generated SQL")
    results: Optional[QueryResult] = Field(default=None, description="Query execution results if valid")
    insights: List[str] = Field(default_factory=list, description="Business insights generated from results")
    chart: Optional[Dict[str, Any]] = Field(default=None, description="Plotly chart configuration JSON")
    session_id: str = Field(..., description="Session identifier")

class DatabaseStatusResponse(BaseModel):
    connected: bool = Field(..., description="Whether the database is connected")
    database: str = Field(default="", description="Name of connected database")
    tables_count: int = Field(default=0, description="Number of tables found")
    message: str = Field(default="", description="Status or error message")

class InsightResponse(BaseModel):
    insights: List[str] = Field(..., description="Generated insights")
    summary: str = Field(..., description="A brief summary of the insights")

class ExplainResponse(BaseModel):
    explanation: str = Field(..., description="Plain English explanation of the SQL")
    tables_used: List[str] = Field(..., description="List of tables used in the query")
    operations: List[str] = Field(..., description="Key operations performed (e.g., JOIN, GROUP BY)")
